### ISSUE TITLE
Custom dataset training

### ISSUE THREAD

**Issue by snarb** [domainadaptation/salad#25]
Hi Steffen! 
I think the common question is how to train a model on my someone own dataset? What are the steps?

**Comment by stes** [comment]
Hi @snarb , sorry for the delay in answering! I recently added a new data loader for the office dataset, which is quite informative of the steps.
Broadly speaking, if you want to apply unsupervised domain adaptation you have to provide data in a format such that iterating over your data loader returns samples for source and target domain, like this:

``` python
for (xs, ys), (xt, _) in mydataloader:
   # [...]
```

The easiest way to get started with this is the ``MultiDomainLoader`` or ``JointLoader`` provided by ``salad.datasets``. Here is a simple example usage for integrating the OfficeDataset:

``` python
class OfficeDataLoader(MultiDomainLoader):
    
    names = ["Amazon", "DSLR", "Webcam"]
    _keys = ["amazon", "dslr", "webcam"]
    
    def __init__(self, path, normalize = False, **kwargs):
        
        dataset = OfficeDataset(path, transform = self.get_transform(normalize = normalize))
        super().__init__(*[DataLoader(d, **kwargs) for d in dataset.datasets], collate="stack")
    
    def get_loader(self, key):
        
        i = self._keys.index(key)
        return self.datasets[i]
        

    def get_transform(self, normalize):

        T = [
            transforms.Resize(224),
            transforms.RandomCrop(224),
            transforms.ToTensor()
        ]
            
        if normalize is True:
            T += [transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])]
            
        return transforms.Compose(T)
```

Note the part initializing the ``MultiDomainLoader`` here:

```
        super().__init__(*[DataLoader(d, **kwargs) for d in dataset.datasets], collate="stack")
```

You pass all data loaders for your different domains, the last arguments determines whether you stack the datasets ("stack") or concatenate them ("cat").
The former returns batches from different datasets as ``(x1,y1), ..., (xn, yn)`` while the latter returns them as ``(x,y,d)`` where `d` takes the value of the domain.

Let me know if you have a specific use case, I am happy to help!

**Comment by stes** [comment]
@snarb, any updates? Will close the issue otherwise

**Comment by stes** [comment]
Closing. Please re-open if further questions arise.
