### ISSUE TITLE
The Datasets SVHN

### ISSUE THREAD

**Issue by A-suozhang** [domainadaptation/salad#37]
The code in salad/datasets/digits/svhn.py could not get svhn, since in the newest pytorch, the Download arg For torchvision.datasets.SVHN is False. Would You fix it to make data loading more elegant? thx A Lot

**Comment by A-suozhang** [comment]
the problem could easily be fixed by downloading the SVHN Dataset in expected dir in advance, so it should not be a problem

**Comment by stes** [comment]
Hello @A-suozhang , thanks for flagging this.

The option in ``salad/datasets/digits/svhn.py`` is simply wrapping ``https://pytorch.org/docs/stable/torchvision/datasets.html#svhn``, thus in case you use the dataset, you have to provide the ``download`` arg yourself. 

Did you come across a code example where the download arg is missing though? That should be corrected.

**Comment by A-suozhang** [comment]
I Directly import the class digitloader, then the error occurs, i didn't seem to quite find the way to feed in arg download when defining the Digitloader. It maybe my problem...

**Comment by A-suozhang** [comment]
Thx For Your Reply, I'm closing this issue
