### ISSUE TITLE
Questions about self-ensemble example

### ISSUE THREAD

**Issue by A-suozhang** [domainadaptation/salad#38]
again thank you for your effort for this amazing repo. when i try to reproduce the self-ensembling method on digits(SVHN,USPS,Mnist) I Could only get the SOTA results seldomly(once in 3~5 times, i guess)for some tough tasks, it could get worse. Have you encountered situation like this when you experiment self-ensembling method on digits datsets, or the training always works?

**Comment by stes** [comment]
Hi @A-suozhang , thanks for using the library! I am happy to dig further into this, can you share the command you use for training so I can try to repro? One possible problem might be the type of augmentation/noise model you use in the training, it might be that the current default options do not reflect what was used in the original paper.

**Comment by A-suozhang** [comment]
Sorry but I only used part of your lib (Dataloading & Augmentation) , I checked later, and the problem is in my own network implemention... the settings you provided works fine. This issue could be closed :)
